DROP TABLE IF EXISTS SUPER_HEROE;
DROP TABLE IF EXISTS SEXO;
DROP TABLE IF EXISTS ORIGEN_PODER;

CREATE TABLE SEXO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(250) NOT NULL
);

CREATE TABLE ORIGEN_PODER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCION VARCHAR(250) NOT NULL
);


CREATE TABLE SUPER_HEROE (
  ID INT PRIMARY KEY,
  NOMBRE VARCHAR(250) NOT NULL,
  SEXO_ID INT,
  ORIGEN_PODER_ID INT,
  PROFESION VARCHAR(250),
  PUEDE_VOLAR VARCHAR(250),
  EDAD INT,
  CONSTRAINT PK_SUPERHEREO PRIMARY KEY (ID)

);







  


